/*
 * Forma — Business-to-Agent Platform (proprietary)
 * Copyright (c) 2026 Forma. All rights reserved.
 */

package forma

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	formahandler "github.com/coze-dev/coze-studio/backend/api/handler/forma"
	"github.com/coze-dev/coze-studio/backend/api/middleware"
)

func Register(r *server.Hertz) {
	root := r.Group("/api")
	v1 := root.Group("/forma/v1", middleware.FormaTenantMW())
	{
		v1.GET("/health", formahandler.Health)
		v1.GET("/version", formahandler.Version)
		v1.GET("/meta/baseline", formahandler.Baseline)

		v1.GET("/me", formahandler.Me)
		v1.GET("/tenants", formahandler.ListTenants)
		v1.POST("/tenants", formahandler.CreateTenant)
		v1.GET("/tenants/:id", formahandler.GetTenant)
		v1.PATCH("/tenants/:id", formahandler.PatchTenant)
		v1.GET("/tenants/:id/members", formahandler.ListMembers)
		v1.POST("/tenants/:id/members", formahandler.AddMember)
		v1.PATCH("/tenants/:id/members/:principalId", formahandler.PatchMember)
		v1.GET("/tenants/:id/spaces", formahandler.ListSpaces)
		v1.POST("/tenants/:id/spaces", formahandler.BindSpace)
		v1.POST("/bootstrap", formahandler.Bootstrap)
		v1.GET("/assets/counts", formahandler.AssetCounts)

		v1.POST("/businesses", formahandler.CreateBusiness)
		v1.GET("/businesses", formahandler.ListBusinesses)
		v1.GET("/businesses/:id", formahandler.GetBusiness)
		v1.PATCH("/businesses/:id", formahandler.PatchBusiness)
		v1.POST("/businesses/:id/archive", formahandler.ArchiveBusiness)
		v1.GET("/businesses/:id/model", formahandler.GetBusinessModel)
		v1.PUT("/businesses/:id/model", formahandler.PutBusinessModel)
		v1.GET("/businesses/:id/revisions", formahandler.ListBusinessRevisions)
		v1.GET("/businesses/:id/revisions/:revision", formahandler.GetBusinessRevision)
		v1.GET("/businesses/:id/diff", formahandler.DiffBusiness)
		v1.GET("/businesses/:id/layout", formahandler.GetBusinessLayout)
		v1.PUT("/businesses/:id/layout", formahandler.PutBusinessLayout)

		v1.POST("/businesses/:id/analyst/sessions", formahandler.CreateAnalystSession)
		v1.GET("/businesses/:id/analyst/sessions", formahandler.ListAnalystSessions)
		v1.GET("/businesses/:id/analyst/sessions/:sessionId", formahandler.GetAnalystSession)
		v1.POST("/businesses/:id/analyst/sessions/:sessionId/turns", formahandler.SubmitAnalystTurn)
		v1.GET("/businesses/:id/analyst/sessions/:sessionId/turns", formahandler.ListAnalystTurns)
		v1.POST("/businesses/:id/analyst/sessions/:sessionId/turns/:turnId/retry-analysis", formahandler.RetryAnalystTurnAnalysis)
		v1.POST("/businesses/:id/analyst/sessions/:sessionId/gaps/:gapId/ask", formahandler.AskAnalystGap)
		v1.GET("/businesses/:id/assertions", formahandler.ListAssertions)
		v1.GET("/businesses/:id/evidence", formahandler.ListBusinessEvidence)
		v1.POST("/businesses/:id/assertions/:assertionId/confirm", formahandler.ConfirmAssertion)
		v1.POST("/businesses/:id/assertions/:assertionId/reject", formahandler.RejectAssertion)
		v1.GET("/businesses/:id/conflicts", formahandler.ListConflicts)
		v1.GET("/businesses/:id/gaps", formahandler.ListGaps)
		v1.POST("/businesses/:id/proposals", formahandler.CreateProposal)
		v1.GET("/businesses/:id/proposals/:proposalId", formahandler.GetProposal)
		v1.GET("/businesses/:id/proposals/:proposalId/preview", formahandler.GetProposalPreview)
		v1.POST("/businesses/:id/proposals/:proposalId/apply", formahandler.ApplyProposal)

		v1.POST("/businesses/:id/data-requirements/analyze", formahandler.AnalyzeDataRequirements)
		v1.GET("/businesses/:id/data-analyses/:analysisRunId", formahandler.GetDataAnalysisRun)
		v1.POST("/businesses/:id/data-analyses/:analysisRunId/retry", formahandler.RetryFailedDataAnalysis)
		v1.GET("/businesses/:id/data-requirements", formahandler.ListDataRequirements)
		v1.POST("/businesses/:id/data-requirements", formahandler.CreateManualDataRequirement)
		v1.POST("/businesses/:id/data-requirements/:requirementId/confirm", formahandler.ConfirmDataRequirement)
		v1.POST("/businesses/:id/data-requirements/:requirementId/reject", formahandler.RejectDataRequirement)
		v1.POST("/businesses/:id/data-requirements/:requirementId/edit-confirm", formahandler.EditConfirmDataRequirement)
		v1.GET("/businesses/:id/data-requirements/:requirementId/decisions", formahandler.ListDataRequirementDecisions)
		v1.POST("/businesses/:id/semantic-mappings/analyze", formahandler.AnalyzeSemanticMappings)
		v1.GET("/businesses/:id/semantic-mapping-analysis/:analysisRunId", formahandler.GetMappingAnalysisRun)
		v1.POST("/businesses/:id/semantic-mapping-analysis/:analysisRunId/retry", formahandler.RetryFailedMappingAnalysis)
		v1.GET("/businesses/:id/semantic-mappings", formahandler.ListSemanticMappings)
		v1.POST("/businesses/:id/semantic-mappings", formahandler.CreateManualSemanticMapping)
		v1.POST("/businesses/:id/semantic-mappings/:mappingId/confirm", formahandler.ConfirmSemanticMapping)
		v1.POST("/businesses/:id/semantic-mappings/:mappingId/reject", formahandler.RejectSemanticMapping)
		v1.POST("/businesses/:id/semantic-mappings/:mappingId/edit-confirm", formahandler.EditConfirmSemanticMapping)
		v1.GET("/businesses/:id/semantic-mappings/:mappingId/decisions", formahandler.ListSemanticMappingDecisions)
		v1.GET("/businesses/:id/semantic-mapping-coverage", formahandler.GetSemanticMappingCoverage)

		v1.POST("/businesses/:id/data-contracts", formahandler.CreateDataContract)
		v1.GET("/businesses/:id/data-contracts", formahandler.ListDataContracts)
		v1.GET("/businesses/:id/data-contracts/:contractId", formahandler.GetDataContract)
		v1.GET("/businesses/:id/data-contracts/:contractId/active-descriptor", formahandler.GetActiveDataContractDescriptor)
		v1.GET("/businesses/:id/data-contracts/:contractId/revisions", formahandler.ListDataContractRevisions)
		v1.POST("/businesses/:id/data-contracts/:contractId/revisions", formahandler.CreateDataContractRevision)
		v1.GET("/businesses/:id/data-contracts/:contractId/revisions/:revisionId", formahandler.GetDataContractRevision)
		v1.POST("/businesses/:id/data-contracts/:contractId/revisions/:revisionId/validate", formahandler.ValidateDataContractRevision)
		v1.POST("/businesses/:id/data-contracts/:contractId/revisions/:revisionId/activate", formahandler.ActivateDataContractRevision)
		v1.POST("/businesses/:id/data-contracts/:contractId/revisions/:revisionId/deprecate", formahandler.DeprecateDataContractRevision)
		v1.GET("/businesses/:id/data-contracts/:contractId/revisions/:revisionId/validation-results", formahandler.ListDataContractValidationResults)
		v1.POST("/businesses/:id/data-contracts/:contractId/revisions/:revisionId/evaluate-drift", formahandler.EvaluateDataContractDrift)
		v1.GET("/businesses/:id/data-contracts/:contractId/revisions/:revisionId/drift-results", formahandler.ListDataContractDriftResults)
		v1.POST("/businesses/:id/data-contracts/:contractId/revisions/:revisionId/evaluate-gap", formahandler.EvaluateDataContractGap)
		v1.GET("/businesses/:id/data-contracts/:contractId/revisions/:revisionId/gap-results", formahandler.ListDataContractGapResults)
		v1.GET("/businesses/:id/data-contracts/:contractId/lifecycle-events", formahandler.ListDataContractLifecycleEvents)

		v1.GET("/data-sources", formahandler.ListDataSources)
		v1.POST("/data-sources", formahandler.CreateDataSource)
		v1.GET("/data-sources/:sourceId", formahandler.GetDataSource)
		v1.PATCH("/data-sources/:sourceId", formahandler.PatchDataSource)
		v1.POST("/data-sources/:sourceId/archive", formahandler.ArchiveDataSource)
		v1.GET("/data-sources/:sourceId/connections", formahandler.ListDataConnections)
		v1.POST("/data-sources/:sourceId/connections", formahandler.CreateDataConnection)
		v1.GET("/data-sources/:sourceId/connections/:connectionId", formahandler.GetDataConnection)
		v1.PATCH("/data-sources/:sourceId/connections/:connectionId", formahandler.PatchDataConnection)
		v1.POST("/data-sources/:sourceId/connections/:connectionId/test", formahandler.TestDataConnection)
		v1.POST("/data-sources/:sourceId/connections/:connectionId/discover", formahandler.DiscoverDataAssets)
		v1.POST("/credentials", formahandler.CreateDataCredential)
		v1.POST("/credentials/:credentialRefId/rotate", formahandler.RotateDataCredential)
		v1.POST("/credentials/:credentialRefId/revoke", formahandler.RevokeDataCredential)
		v1.GET("/data-sources/:sourceId/assets", formahandler.ListDataAssets)
		v1.GET("/data-assets/:assetId", formahandler.GetDataAsset)
		v1.POST("/data-sources/:sourceId/connections/:connectionId/assets/:assetId/capture-schema", formahandler.CaptureDataSchema)
		v1.GET("/schema-snapshots/:snapshotId", formahandler.GetDataSchemaSnapshot)
	}
}
