-- Forma S4-G3: semantic mapping proposals, operational analysis runs, and
-- immutable human decisions. Intentionally no FOREIGN KEY constraints.

CREATE TABLE IF NOT EXISTS `forma_data_semantic_mapping` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `mapping_id` VARCHAR(64) NOT NULL,
  `tenant_id` VARCHAR(64) NOT NULL,
  `business_id` VARCHAR(64) NOT NULL,
  `business_model_revision` INT NOT NULL,
  `requirement_id` VARCHAR(64) NOT NULL,
  `source_id` VARCHAR(64) NOT NULL,
  `connection_id` VARCHAR(64) NOT NULL,
  `asset_id` VARCHAR(64) NOT NULL,
  `schema_snapshot_id` VARCHAR(64) NOT NULL,
  `target_field_paths_json` LONGTEXT NOT NULL,
  `mapping_type` VARCHAR(32) NOT NULL,
  `transform_spec_json` LONGTEXT NOT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'PROPOSED',
  `confirmed_requirement_id` VARCHAR(64) GENERATED ALWAYS AS (CASE WHEN `status` = 'CONFIRMED' THEN `requirement_id` ELSE NULL END) STORED,
  `source` VARCHAR(32) NOT NULL,
  `confidence` DOUBLE NOT NULL DEFAULT 0,
  `reason` TEXT NOT NULL,
  `derived_from_mapping_id` VARCHAR(64) NOT NULL DEFAULT '',
  `analysis_run_id` VARCHAR(64) NOT NULL DEFAULT '',
  `created_by` VARCHAR(64) NOT NULL,
  `created_at` DATETIME(3) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_forma_data_semantic_mapping` (`tenant_id`, `mapping_id`),
  UNIQUE KEY `uk_forma_data_mapping_confirmed_requirement` (`tenant_id`, `business_id`, `business_model_revision`, `confirmed_requirement_id`),
  KEY `idx_forma_data_semantic_mapping_scope` (`tenant_id`, `business_id`, `business_model_revision`, `requirement_id`, `status`),
  KEY `idx_forma_data_semantic_mapping_analysis` (`tenant_id`, `analysis_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `forma_data_semantic_mapping_analysis_run` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `analysis_run_id` VARCHAR(64) NOT NULL,
  `tenant_id` VARCHAR(64) NOT NULL,
  `business_id` VARCHAR(64) NOT NULL,
  `business_model_revision` INT NOT NULL,
  `client_request_id` VARCHAR(128) NOT NULL,
  `request_digest` VARCHAR(64) NOT NULL,
  `request_json` LONGTEXT NOT NULL,
  `status` VARCHAR(16) NOT NULL,
  `model_ref` VARCHAR(256) NOT NULL DEFAULT '',
  `error_key` VARCHAR(128) NOT NULL DEFAULT '',
  `error_message_sanitized` VARCHAR(1024) NOT NULL DEFAULT '',
  `retry_count` INT NOT NULL DEFAULT 0,
  `last_retry_by` VARCHAR(64) NOT NULL DEFAULT '',
  `last_retry_at` DATETIME(3) NULL,
  `execution_generation` INT NOT NULL DEFAULT 1,
  `execution_claimed_at` DATETIME(3) NULL,
  `lease_expires_at` DATETIME(3) NULL,
  `created_by` VARCHAR(64) NOT NULL,
  `started_at` DATETIME(3) NULL,
  `completed_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_forma_data_mapping_analysis_run` (`tenant_id`, `analysis_run_id`),
  UNIQUE KEY `uk_forma_data_mapping_analysis_idempotency` (`tenant_id`, `business_id`, `business_model_revision`, `client_request_id`),
  KEY `idx_forma_data_mapping_analysis_status` (`tenant_id`, `business_id`, `business_model_revision`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `forma_data_semantic_mapping_decision` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `decision_id` VARCHAR(64) NOT NULL,
  `tenant_id` VARCHAR(64) NOT NULL,
  `business_id` VARCHAR(64) NOT NULL,
  `source_mapping_id` VARCHAR(64) NOT NULL,
  `target_mapping_id` VARCHAR(64) NOT NULL DEFAULT '',
  `action` VARCHAR(32) NOT NULL,
  `actor_principal_id` VARCHAR(64) NOT NULL,
  `reason` TEXT NOT NULL,
  `business_model_revision` INT NOT NULL,
  `created_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_forma_data_mapping_decision` (`tenant_id`, `decision_id`),
  UNIQUE KEY `uk_forma_data_mapping_decision_source` (`tenant_id`, `source_mapping_id`),
  KEY `idx_forma_data_mapping_decision_target` (`tenant_id`, `target_mapping_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
